"""add knowledge graph

Revision ID: 47881f3a7239
Revises: 58dd87e6a22a
Create Date: 2026-09-13 20:48:43.567116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '47881f3a7239'
down_revision: Union[str, Sequence[str], None] = '58dd87e6a22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('module', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=30), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('source_pages', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_nodes_course_id'), 'graph_nodes', ['course_id'], unique=False)
    op.create_index(op.f('ix_graph_nodes_node_id'), 'graph_nodes', ['node_id'], unique=True)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('from_node', sa.String(length=255), nullable=False),
    sa.Column('to_node', sa.String(length=255), nullable=False),
    sa.Column('relation', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['from_node'], ['graph_nodes.node_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node'], ['graph_nodes.node_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_edges_course_id'), 'graph_edges', ['course_id'], unique=False)
    op.create_index(op.f('ix_graph_edges_from_node'), 'graph_edges', ['from_node'], unique=False)
    op.create_index(op.f('ix_graph_edges_to_node'), 'graph_edges', ['to_node'], unique=False)
    op.add_column('content_chunks', sa.Column('node_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_content_chunks_node_id'), 'content_chunks', ['node_id'], unique=False)
    op.create_foreign_key(None, 'content_chunks', 'graph_nodes', ['node_id'], ['node_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content_chunks', type_='foreignkey')
    op.drop_index(op.f('ix_content_chunks_node_id'), table_name='content_chunks')
    op.drop_column('content_chunks', 'node_id')
    op.drop_index(op.f('ix_graph_edges_to_node'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_from_node'), table_name='graph_edges')
    op.drop_index(op.f('ix_graph_edges_course_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_graph_nodes_node_id'), table_name='graph_nodes')
    op.drop_index(op.f('ix_graph_nodes_course_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    # ### end Alembic commands ###