"""add ai interaction logging

Revision ID: 58dd87e6a22a
Revises: d2643e072730
Create Date: 2026-09-13 20:31:42.097007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58dd87e6a22a'
down_revision: Union[str, Sequence[str], None] = 'd2643e072730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###