"""prevent duplicate active subscriptions

Revision ID: e13c98b708fa
Revises: 2b7be2606975
Create Date: 2026-09-13 00:49:34.026865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13c98b708fa'
down_revision: Union[str, Sequence[str], None] = '2b7be2606975'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_active_or_pending_subscription', 'subscriptions', ['user_id', 'course_id'], unique=True, postgresql_where=sa.text("status IN ('pending', 'active')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_active_or_pending_subscription', table_name='subscriptions', postgresql_where=sa.text("status IN ('pending', 'active')"))
    # ### end Alembic commands ###